// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpntlozvucbsclhfjpko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwbnRsb3p2dWNic2NsaGZqcGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDAzNzAsImV4cCI6MjA3MjUxNjM3MH0.42Nbs5rbZC9Bv4IOPQPsL3fqORWAuEDjAbnHqGxUB_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});